style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false
naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
OtusRuleSet:
  ComposeModifierRule:
    active: true
  GlobalScopeRule:
    active: true
  TopLevelCoroutineInSuspendFunRule:
    active: true
  CoroutineWithoutDispatcherRule:
    active: true
