OtusRuleSet:
  ComposeModifierMissingRule:
    active: true
  GlobalScopeRule:
    active: true
  TopLevelCoroutineInSuspendFunRule:
    active: true
  CoroutineWithoutDispatcherRule:
    active: true
